In [20]:
import numpy as np

X = np.array([[2,1], [0,2] ]).T
W = np.array([[2,1,-.5], [0, 1, 3]]).T
W@X

array([[4., 0.],
       [3., 2.],
       [2., 6.]])

In [22]:
from numpy import log
def softmax(z): 
    return np.exp(z)/np.exp(z).sum()

def crossentropyLoss(y, yp):
    return y*log(yp) + (1-y)*log(1-yp)

crossentropyLoss(1,0)

/var/folders/ys/c56_nbzj0xqfczrwy5t7mpvm0000gn/T/ipykernel_85844/539627818.py:6: RuntimeWarning: divide by zero encountered in log
  return y*log(yp) + (1-y)*log(1-yp)


-inf

In [21]:
for col in (W@X).T:
    print(col, softmax(col))
    

[4. 3. 2.] [0.66524096 0.24472847 0.09003057]
[0. 2. 6.] [0.00242826 0.01794253 0.97962921]


In [9]:
W

array([[ 2. ,  3. ],
       [ 1. ,  1. ],
       [-0.5,  0. ]])

In [12]:
col

array([4., 5.])

In [13]:
softmax(col)

TypeError: unsupported operand type(s) for /: 'float' and 'builtin_function_or_method'

In [16]:
(W@X).T

array([[ 7.,  3., -1.],
       [ 3.,  1.,  0.]])